# Generated by Django 3.2.12 on 2022-02-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('which_line', models.IntegerField()),
                ('count_of_customers', models.IntegerField()),
            ],
        ),
    ]
