# Generated by Django 3.2.12 on 2022-02-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='which_line',
            new_name='line_id',
        ),
        migrations.AlterField(
            model_name='line',
            name='count_of_customers',
            field=models.CharField(max_length=80),
        ),
    ]
