# Generated by Django 3.2.12 on 2022-02-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0002_auto_20220202_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('customer_name', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Line',
        ),
    ]
